<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-24T02:10:35 IST" name="Suite" finished-at="2025-03-24T02:10:47 IST" duration-ms="12208">
    <groups>
    </groups>
    <test started-at="2025-03-24T02:10:35 IST" name="Error Validation Test" finished-at="2025-03-24T02:10:42 IST" duration-ms="7412">
      <class name="mavenPractice.errorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:mavenPractice.errorValidationTest@1f59a598]" started-at="2025-03-24T02:10:35 IST" name="launchApplication" finished-at="2025-03-24T02:10:38 IST" duration-ms="2699" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="correctCredential()[pri:0, instance:mavenPractice.errorValidationTest@1f59a598]" started-at="2025-03-24T02:10:38 IST" name="correctCredential" finished-at="2025-03-24T02:10:40 IST" duration-ms="2220" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- correctCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:mavenPractice.errorValidationTest@1f59a598]" started-at="2025-03-24T02:10:40 IST" name="tearDown" finished-at="2025-03-24T02:10:40 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:mavenPractice.errorValidationTest@1f59a598]" started-at="2025-03-24T02:10:40 IST" name="launchApplication" finished-at="2025-03-24T02:10:42 IST" duration-ms="1367" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="errorValidation()[pri:0, instance:mavenPractice.errorValidationTest@1f59a598]" started-at="2025-03-24T02:10:42 IST" name="errorValidation" finished-at="2025-03-24T02:10:42 IST" duration-ms="543" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:mavenPractice.errorValidationTest@1f59a598]" started-at="2025-03-24T02:10:42 IST" name="tearDown" finished-at="2025-03-24T02:10:42 IST" duration-ms="258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- mavenPractice.errorValidationTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2025-03-24T02:10:35 IST" name="Submit order test" finished-at="2025-03-24T02:10:47 IST" duration-ms="12208">
      <class name="mavenPractice.ecommerceUITest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:mavenPractice.ecommerceUITest@40a4337a]" started-at="2025-03-24T02:10:35 IST" name="launchApplication" finished-at="2025-03-24T02:10:38 IST" duration-ms="3057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="createOrder()[pri:0, instance:mavenPractice.ecommerceUITest@40a4337a]" started-at="2025-03-24T02:10:38 IST" name="createOrder" finished-at="2025-03-24T02:10:43 IST" duration-ms="5289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:mavenPractice.ecommerceUITest@40a4337a]" started-at="2025-03-24T02:10:43 IST" name="tearDown" finished-at="2025-03-24T02:10:44 IST" duration-ms="265" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:mavenPractice.ecommerceUITest@40a4337a]" started-at="2025-03-24T02:10:44 IST" name="launchApplication" finished-at="2025-03-24T02:10:46 IST" duration-ms="2334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="dependencyCode()[pri:0, instance:mavenPractice.ecommerceUITest@40a4337a]" started-at="2025-03-24T02:10:46 IST" name="dependencyCode" finished-at="2025-03-24T02:10:47 IST" depends-on-methods="mavenPractice.ecommerceUITest.createOrder" duration-ms="920" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [You have No Orders to show at this time. Please Visit Back Us] but found [You have No Orders to show at this time.
Please Visit Back Us]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [You have No Orders to show at this time. Please Visit Back Us] but found [You have No Orders to show at this time.
Please Visit Back Us]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at mavenPractice.ecommerceUITest.dependencyCode(ecommerceUITest.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dependencyCode -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:mavenPractice.ecommerceUITest@40a4337a]" started-at="2025-03-24T02:10:47 IST" name="tearDown" finished-at="2025-03-24T02:10:47 IST" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- mavenPractice.ecommerceUITest -->
    </test> <!-- Submit order test -->
  </suite> <!-- Suite -->
</testng-results>
